config/routes.rb
Rails.application.routes.draw do
  get 'static_pages/home'
  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'
  resources :messages
  resources :members
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root "static_pages#home"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/key.rb
class Key < ApplicationRecord
	validate :count_within_limit
	def count_within_limit
		if Key.count > 1
			raise "Cannot have more than 1 key"
		end
	end 
end

app/models/member.rb
class Member < ApplicationRecord
	validates :name, presence: true
	validates :phone, presence: true 
	validates :name, length: {in: 1..20}
	validates :phone, length: {is: 12}
end

app/models/message.rb
class Message < ApplicationRecord
	validates :sender_id, presence: true 
	validates :content, presence: true 
	validates :content, length: { in: 1..100 }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  include SessionsHelper
  def hello
  	render html: "What be up world?!"
  end
end

app/controllers/members_controller.rb
class MembersController < ApplicationController
  include SessionsHelper
  before_action :set_member, :check_expire, only: [:show, :edit, :update, :destroy]
  # GET /members.json
  def index
    @members = Member.all
  end

  # GET /members/1
  # GET /members/1.json
  def show
  end

  # GET /members/new
  def new
    @member = Member.new
  end

  # GET /members/1/edit
  def edit
  end

  # POST /members
  # POST /members.json
  def create
    temp = params.require(:member)
    @member = Member.new(:name => temp[:name], :phone => "+1" + temp[:phone])
    respond_to do |format|
      if @member.save
        format.html { redirect_to @member, notice: 'Member was successfully created.' }
        format.json { render :show, status: :created, location: @member }
      else
        format.html { render :new }
        format.json { render json: @member.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /members/1
  # PATCH/PUT /members/1.json
  def update
    respond_to do |format|
      if @member.update(member_params)
        format.html { redirect_to @member, notice: 'Member was successfully updated.' }
        format.json { render :show, status: :ok, location: @member }
      else
        format.html { render :edit }
        format.json { render json: @member.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /members/1
  # DELETE /members/1.json
  def destroy
    @member.destroy
    respond_to do |format|
      format.html { redirect_to members_url, notice: 'Member was successfully destroyed.' }
      format.json { head :no_content }
    end
  end



  private
    # Use callbacks to share common setup or constraints between actions.
    def set_member
      @member = Member.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def member_params
      params.require(:member).permit(:name, :phone)
    end
end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController
  include SessionsHelper
  before_action :set_message, :check_expire, only: [:show, :edit, :update, :destroy]

  # GET /messages
  # GET /messages.json
  def index
    @messages = Message.all
  end

  # GET /messages/1
  # GET /messages/1.json
  def show
  end

  # GET /messages/new
  def new
    @message = Message.new
  end

  # GET /messages/1/edit
  def edit
  end

  # POST /messages
  # POST /messages.json
  def create
    temp = params.require(:message)
    date = String(Time.now.inspect)[0..18] #trims/formats the Time 
    @message = Message.new(:date => date, :content => temp[:content], :sender_id => temp[:sender_id])
    respond_to do |format|
      if @message.save
        send_message_to_all(temp[:sender_id], temp[:content], date)
        format.html { redirect_to @message, notice: 'Message was successfully created.' }
        format.json { render :show, status: :created, location: @message }
      else
        format.html { render :new }
        format.json { render json: @message.errors, status: :unprocessable_entity }
      end
    end
  end

  def send_message_to_all(sender, text, date)
    load 'account_info.rb'
    @client = Twilio::REST::Client.new $account_sid, $auth_token
    Member.all.each do |member|
      @client.account.messages.create({
        :from => $phone_num,
        :to => member.phone, 
        :body => "-DO NOT REPLY-\n" + "From " + sender + ":\n" + text + "\n" + date
      })
    end 
  end

  # PATCH/PUT /messages/1
  # PATCH/PUT /messages/1.json
  def update
    respond_to do |format|
      if @message.update(message_params)
        format.html { redirect_to @message, notice: 'Message was successfully updated.' }
        format.json { render :show, status: :ok, location: @message }
      else
        format.html { render :edit }
        format.json { render json: @message.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /messages/1
  # DELETE /messages/1.json
  def destroy
    @message.destroy
    respond_to do |format|
      format.html { redirect_to messages_url, notice: 'Message was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_message
      @message = Message.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def message_params
      params.require(:message).permit(:date, :content, :sender_id)
    end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end
  def create
  	key = Key.find_by(key: params[:session][:key])
  	if key != nil 
  	  #login
  	  log_in key
  	  redirect_to static_pages_home_url
  	else
  	  flash.now[:danger] = 'Invalid key!' # Not quite right!
  	  render 'new'
  	end 

  end
  def destroy
  	log_out
  end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
	include SessionsHelper
	before_action :authenticate, :check_expire
	def authenticate
		unless logged_in? 
	  		redirect_to(login_url)
	  	end 
	end

  def home
  end

  def help
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
	# Returns the full title on a per-page basis.
  def full_title(page_title = '')
    base_title = "Blast"
    if page_title.empty?
      base_title
    else
      page_title + " | " + base_title
    end
  end
end

app/helpers/members_helper.rb
module MembersHelper
end

app/helpers/messages_helper.rb
module MessagesHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
  @current_key = nil 
	def log_in(key)
		session[:key_id] = key.id
    session[:expire] = Time.now + 5.minutes 
    @current_key = key 
	end 
	def log_out
		session.delete(:key_id)
    session.delete(:expire)
    @current_key = nil
  end 

	def current_key
    @current_key ||= Key.find_by(id: session[:key_id])
  end
  # Returns true if the user is logged in, false otherwise.
  def logged_in?
    !current_key.nil?
  end

  def check_expire
    if session.has_key?(:expire)
      if Time.now > session[:expire]
        log_out
      end
    end
  end 
end 

app/helpers/static_pages_helper.rb
module StaticPagesHelper
	
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= full_title(yield(:title)) %></title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/members/_form.html.erb
<%= form_with(model: member, local: true) do |form| %>
  <% if member.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(member.errors.count, "error") %> prohibited this member from being saved:</h2>

      <ul>
      <% member.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name, id: :member_name %>
  </div>

  <div class="field">
    <%= form.label :phone%>
    <%= form.text_field :phone, id: :member_phone %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/members/edit.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
      <div class="container">
        <%= link_to "Blast", '#', id: "logo" %>
        <nav>
          <ul class="nav navbar-nav navbar-right">
            <li> <a href = "/static_pages/home"> Home</a> </li>
            <li> <a href = "/members"> Members </a> </li>
            <li><a href = "/messages"> Messages </a> </li>
          </ul>
        </nav>
      </div>
    </header>
<h1>Editing Member</h1>

<%= render 'form', member: @member %>

<%= link_to 'Show', @member %> |
<%= link_to 'Back', members_path %>

app/views/members/index.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
      <div class="container">
        <%= link_to "Blast", '#', id: "logo" %>
        <nav>
          <ul class="nav navbar-nav navbar-right">
            <li> <a href = "/static_pages/home"> Home</a> </li>
            <li> <a href = "/members"> Members </a> </li>
            <li><a href = "/messages"> Messages </a> </li>
          </ul>
        </nav>
      </div>
</header>
<p id="notice"><%= notice %></p>

<h1>Members</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Phone</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @members.each do |member| %>
      <tr>
        <td><%= member.name %></td>
        <td><%= member.phone %></td>
        <td><%= link_to 'Show', member %></td>
        <!-- <td><%= link_to 'Edit', edit_member_path(member) %></td> -->
        <td><%= link_to 'Destroy', member, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<a class= "btn btn-lg btn-success"  href = "/members/new"> New Member </a>

app/views/members/new.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
      <div class="container">
        <%= link_to "Blast", '#', id: "logo" %>
        <nav>
          <ul class="nav navbar-nav navbar-right">
            <li> <a href = "/static_pages/home"> Home</a> </li>
            <li> <a href = "/members"> Members </a> </li>
            <li><a href = "/messages"> Messages </a> </li>
          </ul>
        </nav>
      </div>
    </header>
<h1>New Member</h1>

<%= render 'form', member: @member %>

<%= link_to 'Back', members_path %>

app/views/members/show.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
      <div class="container">
        <%= link_to "Blast", '#', id: "logo" %>
        <nav>
          <ul class="nav navbar-nav navbar-right">
            <li> <a href = "/static_pages/home"> Home</a> </li>
            <li> <a href = "/members"> Members </a> </li>
            <li><a href = "/messages"> Messages </a> </li>
          </ul>
        </nav>
      </div>
    </header>
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @member.name %>
</p>

<p>
  <strong>Phone:</strong>
  <%= @member.phone %>
</p>

<%= link_to 'Edit', edit_member_path(@member) %> |
<%= link_to 'Back', members_path %>

app/views/messages/_form.html.erb
<%= form_with(model: message, local: true) do |form| %>
  <% if message.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(message.errors.count, "error") %> prohibited this message from being saved:</h2>

      <ul>
      <% message.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :content %>
    <%= form.text_area :content, id: :message_content %>
  </div>

  <div class="field">
    <%= form.label :sender_id %>
    <%= form.text_area :sender_id, id: :message_sender_id %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/messages/edit.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
      <div class="container">
        <%= link_to "Blast", '#', id: "logo" %>
        <nav>
          <ul class="nav navbar-nav navbar-right">
            <li> <a href = "/static_pages/home"> Home</a> </li>
            <li> <a href = "/members"> Members </a> </li>
            <li><a href = "/messages"> Messages </a> </li>
          </ul>
        </nav>
      </div>
    </header>
<h1>Editing Message</h1>

<%= render 'form', message: @message %>

<%= link_to 'Show', @message %> |
<%= link_to 'Back', messages_path %>

app/views/messages/index.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
      <div class="container">
        <%= link_to "Blast", '#', id: "logo" %>
        <nav>
          <ul class="nav navbar-nav navbar-right">
            <li> <a href = "/static_pages/home"> Home</a> </li>
            <li> <a href = "/members"> Members </a> </li>
            <li><a href = "/messages"> Messages </a> </li>
          </ul>
        </nav>
      </div>
    </header>
<p id="notice"><%= notice %></p>

<h1>Messages</h1>

<table>
  <thead>
    <tr>
      <th>Date</th>
      <th>Content</th>
      <th>Sender</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @messages.each do |message| %>
      <tr>
        <td><%= message.date %></td>
        <td><%= message.content %></td>
        <td><%= message.sender_id %></td>
        <td><%= link_to 'Show', message %></td>
        <!-- <td><%= link_to 'Edit', edit_message_path(message) %></td> -->
        <!-- <td><%= link_to 'Destroy', message, method: :delete, data: { confirm: 'Are you sure?' } %></td> -->
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<a class= "btn btn-lg btn-success"  href = "/messages/new"> New Message </a>

app/views/messages/new.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
      <div class="container">
        <%= link_to "Blast", '#', id: "logo" %>
        <nav>
          <ul class="nav navbar-nav navbar-right">
            <li> <a href = "/static_pages/home"> Home</a> </li>
            <li> <a href = "/members"> Members </a> </li>
            <li><a href = "/messages"> Messages </a> </li>
          </ul>
        </nav>
      </div>
    </header>
<h1>New Message</h1>

<%= render 'form', message: @message %>

<%= link_to 'Back', messages_path %>

app/views/messages/show.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
      <div class="container">
        <%= link_to "Blast", '#', id: "logo" %>
        <nav>
          <ul class="nav navbar-nav navbar-right">
            <li> <a href = "/static_pages/home"> Home</a> </li>
            <li> <a href = "/members"> Members </a> </li>
            <li><a href = "/messages"> Messages </a> </li>
          </ul>
        </nav>
      </div>
    </header>
<p id="notice"><%= notice %></p>

<p>
  <strong>Date:</strong>
  <%= @message.date %>
</p>

<p>
  <strong>Content:</strong>
  <%= @message.content %>
</p>

<p>
  <strong>Sender:</strong>
  <%= @message.sender_id %>
</p>

<%= link_to 'Edit', edit_message_path(@message) %> |
<%= link_to 'Back', messages_path %>

app/views/static_pages/home.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= full_title(yield(:title)) %></title>
    <%= csrf_meta_tags %>
    <%= stylesheet_link_tag    'application', media: 'all',
                                              'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <!--[if lt IE 9]>
      <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/r29/html5.min.js">
      </script>
    <![endif]-->
  </head>
  <body>
    <header class="navbar navbar-fixed-top navbar-inverse">
      <div class="container">
        <%= link_to "Blast", '#', id: "logo" %>
        <nav>
          <ul class="nav navbar-nav navbar-right">
            <li> <a href = "/static_pages/home"> Home</a> </li>
            <li> <a href = "/members"> Members </a> </li>
            <li><a href = "/messages"> Messages </a> </li>
          </ul>
        </nav>
      </div>
    </header>
    <div class="container">
      <%= yield %>
    </div>
    <div class="center jumbotron">
  		<h1>Welcome to Blast</h1>
      <h2> An easier way to notify your house in times of urgency </h2>
		  <a class= "btn btn-lg btn-success"  href = "/messages/new"> New Message </a>
	  </div>
    <!-- <div class = "letters"> 
      <img src = <%= image_url("letters.png")%> class = "imgCenter">
      <img src = <%= image_url("crest.jpg")%> class = "imgCenter">  
    </div>
    <h3 class = "delta"> Delta Chapter est. 1988 </h3> -->
</body>
</html>

app/views/static_pages/login.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= full_title(yield(:title)) %></title>
    <%= csrf_meta_tags %>
    <%= stylesheet_link_tag    'application', media: 'all',
                                              'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <!--[if lt IE 9]>
      <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/r29/html5.min.js">
      </script>
    <![endif]-->
  </head>
  <body>
    <header class="navbar navbar-fixed-top navbar-inverse">
      <div class="container">
        <%= link_to "Blast", '#', id: "logo" %>
        <nav>
        </nav>
      </div>
    </header>
    <div class="container">
      <%= yield %>
    </div>
    <div class="center jumbotron">
  		<h1>Welcome to Blast</h1>
      <h2> An easier way to notify your house in times of urgency </h2>
		  <p> Enter your access key: </p> 
	  </div>
    <!-- <div class = "letters"> 
      <img src = <%= image_url("letters.png")%> class = "imgCenter">
      <img src = <%= image_url("crest.jpg")%> class = "imgCenter">  
    </div>
    <h3 class = "delta"> Delta Chapter est. 1988 </h3> -->
</body>
</html>